authors:
  akshay:
    name: Akshay Ballal
    description: Creator of EmbedAnything
    avatar: https://pbs.twimg.com/profile_images/1660187462357127168/6dV9SpLi_400x400.jpg
  sonam:
    name: Sonam Pankaj
    description: Creator of EmbedAnything
    avatar: https://pbs.twimg.com/profile_images/1961327674044907520/-bgQKKlr_400x400.jpg